# Generated by Django 6.0 on 2025-12-24 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('stripe', 'Stripe'), ('midtrans', 'Midtrans'), ('xendit', 'Xendit'), ('manual_transfer', 'Transfer Manual')], max_length=30, unique=True)),
                ('display_name', models.CharField(help_text='Name shown to users, e.g. "Transfer Bank BCA"', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class, e.g. "fas fa-credit-card"', max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('supports_subscription', models.BooleanField(default=False, help_text='Whether this provider supports recurring payments')),
                ('supports_refund', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('supported_currencies', models.JSONField(default=list, help_text='List of supported currencies, e.g. ["IDR", "USD"]')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum transaction amount', max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum transaction amount (null for no limit)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Provider',
                'verbose_name_plural': 'Payment Providers',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='bank_logos/')),
                ('instructions', models.TextField(blank=True, help_text='Transfer instructions to display to users')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('provider', models.ForeignKey(limit_choices_to={'provider_type': 'manual_transfer'}, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='payments.paymentprovider')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['display_order', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('course', 'Single Course'), ('bundle', 'Course Bundle'), ('subscription', 'Subscription')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('awaiting_verification', 'Awaiting Verification'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=25)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('payment_proof', models.ImageField(blank=True, upload_to='payment_proofs/%Y/%m/')),
                ('transfer_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount user claims to have transferred', max_digits=10, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Payment deadline for pending orders', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.bankaccount')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_orders', to=settings.AUTH_USER_MODEL)),
                ('payment_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.paymentprovider')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_or_user_id_0f08a8_idx'), models.Index(fields=['order_number'], name='payments_or_order_n_80ab42_idx'), models.Index(fields=['status', 'created_at'], name='payments_or_status_99bb2e_idx'), models.Index(fields=['payment_provider', 'status'], name='payments_or_payment_5c9d18_idx')],
            },
        ),
    ]
