# Generated by Django 6.0 on 2025-12-24 13:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Platform commission percentage (e.g., 20 for 20%)', max_digits=5)),
                ('minimum_payout', models.DecimalField(decimal_places=2, default=Decimal('500000'), help_text='Minimum balance required to request payout', max_digits=10)),
                ('payout_requires_approval', models.BooleanField(default=True, help_text='Whether payouts need admin approval')),
                ('default_currency', models.CharField(default='IDR', max_length=3)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_account_holder', models.CharField(max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instructor_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('is_paid_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='payments.order')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='payments.payout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['instructor', 'status'], name='payments_pa_instruc_df9922_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'requested_at'], name='payments_pa_status_7e09a4_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorearning',
            index=models.Index(fields=['instructor', 'is_paid_out'], name='payments_in_instruc_65710b_idx'),
        ),
        migrations.AddIndex(
            model_name='instructorearning',
            index=models.Index(fields=['instructor', 'created_at'], name='payments_in_instruc_8d74ef_idx'),
        ),
    ]
