# Generated by Django 5.2.6 on 2025-10-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('staff', 'Staff')], default='student', help_text='User role in the LMS', max_length=20),
        ),
    ]
