# Generated by Django 6.0 on 2025-12-26 15:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ta3lem LMS', help_text='Name of your LMS platform', max_length=200)),
                ('site_tagline', models.CharField(blank=True, default='Platform Belajar Online Terdepan', help_text='Tagline shown on landing page', max_length=500)),
                ('site_description', models.TextField(blank=True, default='Tingkatkan keahlian masa depanmu dengan kursus berkualitas', help_text='Site description for SEO')),
                ('contact_email', models.EmailField(default='support@ta3lem.com', help_text='Main contact email for support', max_length=254)),
                ('enable_subscriptions', models.BooleanField(default=True, help_text='Enable subscription-based access to courses')),
                ('enable_one_time_purchase', models.BooleanField(default=True, help_text='Enable one-time course purchases')),
                ('enable_free_courses', models.BooleanField(default=True, help_text='Allow free courses on the platform')),
                ('enable_course_certificates', models.BooleanField(default=True, help_text='Enable certificate generation for completed courses')),
                ('enable_course_reviews', models.BooleanField(default=True, help_text='Allow students to review courses')),
                ('enable_discussion_forums', models.BooleanField(default=True, help_text='Enable discussion forums for courses')),
                ('enable_waitlist', models.BooleanField(default=True, help_text='Enable course waitlist when capacity is reached')),
                ('enable_instructor_earnings', models.BooleanField(default=True, help_text='Enable earnings system for instructors')),
                ('require_email_verification', models.BooleanField(default=True, help_text='Require email verification before enrollment')),
                ('auto_enroll_free_courses', models.BooleanField(default=True, help_text='Automatically enroll students in free courses (no approval)')),
                ('max_enrollments_per_student', models.PositiveIntegerField(default=0, help_text='Maximum courses a student can enroll in (0 = unlimited)')),
                ('subscription_trial_enabled', models.BooleanField(default=True, help_text='Allow trial periods for subscriptions')),
                ('subscription_trial_days', models.PositiveIntegerField(default=7, help_text='Default trial period in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('subscription_grace_period_days', models.PositiveIntegerField(default=3, help_text='Grace period after subscription expires before revoking access', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('subscription_auto_renew', models.BooleanField(default=True, help_text='Enable auto-renewal for subscriptions')),
                ('payment_currency', models.CharField(choices=[('IDR', 'Indonesian Rupiah'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='IDR', help_text='Default currency for payments', max_length=3)),
                ('minimum_payout_amount', models.DecimalField(decimal_places=2, default=100000, help_text='Minimum amount for instructor payout requests (in default currency)', max_digits=10)),
                ('platform_commission_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Platform commission percentage on course sales', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_course_capacity', models.PositiveIntegerField(default=0, help_text='Default maximum enrollment capacity for courses (0 = unlimited)')),
                ('require_course_approval', models.BooleanField(default=False, help_text='Require admin approval before courses are published')),
                ('min_course_price', models.DecimalField(decimal_places=2, default=0, help_text='Minimum price for paid courses', max_digits=10)),
                ('max_course_price', models.DecimalField(decimal_places=2, default=10000000, help_text='Maximum price for paid courses', max_digits=10)),
                ('max_video_size_mb', models.PositiveIntegerField(default=500, help_text='Maximum video upload size in MB')),
                ('max_file_size_mb', models.PositiveIntegerField(default=50, help_text='Maximum file upload size in MB')),
                ('allowed_video_formats', models.CharField(default='mp4,webm,avi,mov', help_text='Allowed video formats (comma-separated)', max_length=200)),
                ('allowed_file_formats', models.CharField(default='pdf,doc,docx,ppt,pptx,xls,xlsx,zip', help_text='Allowed file formats for downloads (comma-separated)', max_length=200)),
                ('send_enrollment_notifications', models.BooleanField(default=True, help_text='Send email notifications on enrollment')),
                ('send_completion_notifications', models.BooleanField(default=True, help_text='Send email notifications on course completion')),
                ('send_subscription_notifications', models.BooleanField(default=True, help_text='Send email notifications for subscription events')),
                ('send_payment_notifications', models.BooleanField(default=True, help_text='Send email notifications for payment events')),
                ('subscription_expiry_reminder_days', models.PositiveIntegerField(default=7, help_text='Days before expiry to send reminder email')),
                ('meta_keywords', models.CharField(blank=True, default='online learning, courses, education, skills', help_text='Meta keywords for SEO (comma-separated)', max_length=500)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., G-XXXXXXXXXX)', max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='Facebook Pixel ID for tracking', max_length=50)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn page URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (site inaccessible except for admins)')),
                ('maintenance_message', models.TextField(blank=True, default='We are currently performing maintenance. Please check back soon.', help_text='Message shown during maintenance mode')),
                ('show_stats_section', models.BooleanField(default=True, help_text='Show statistics section on landing page')),
                ('show_featured_courses', models.BooleanField(default=True, help_text='Show featured courses section on landing page')),
                ('show_testimonials', models.BooleanField(default=True, help_text='Show testimonials section on landing page')),
                ('show_pricing', models.BooleanField(default=True, help_text='Show pricing section on landing page')),
                ('featured_courses_count', models.PositiveIntegerField(default=6, help_text='Number of featured courses to show on landing page', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60, help_text='User session timeout in minutes')),
                ('cache_timeout_seconds', models.PositiveIntegerField(default=300, help_text='Default cache timeout in seconds')),
                ('enable_debug_mode', models.BooleanField(default=False, help_text='⚠️ Enable debug mode (DO NOT use in production!)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
