# Generated by Django 6.0 on 2026-01-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='allow_instructor_registration',
            field=models.BooleanField(default=True, help_text='Allow users to self-register as instructors'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='instructor_mode',
            field=models.CharField(choices=[('single', 'Single Instructor per Course'), ('multiple', 'Multiple Instructors per Course')], default='single', help_text='single: 1 owner per course. multiple: courses can have co-instructors', max_length=20),
        ),
    ]
