# Generated by Django 6.0 on 2026-01-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique identifier for the plugin', max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether the plugin is currently active')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Plugin-specific configuration as JSON')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plugin Configuration',
                'verbose_name_plural': 'Plugin Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PluginHookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_name', models.CharField(db_index=True, max_length=100)),
                ('plugin_name', models.CharField(blank=True, max_length=100)),
                ('execution_time_ms', models.FloatField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plugin Hook Log',
                'verbose_name_plural': 'Plugin Hook Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hook_name', 'created_at'], name='plugins_plu_hook_na_8fa9b4_idx')],
            },
        ),
    ]
