"""
Courses API package.
"""

from .serializers import (
    SubjectSerializer,
    SubjectDetailSerializer,
    CourseListSerializer,
    CourseDetailSerializer,
    CourseCreateSerializer,
    ModuleSerializer,
    ModuleDetailSerializer,
    ModuleCreateSerializer,
    ContentSerializer,
    ContentCreateSerializer,
    ContentItemSerializer,
    TextSerializer,
    VideoSerializer,
    ImageSerializer,
    FileSerializer,
    CourseEnrollmentSerializer,
    EnrollmentCreateSerializer,
    CourseWaitlistSerializer,
    ContentProgressSerializer,
    ModuleProgressSerializer,
    LearningSessionSerializer,
    MarkContentCompleteSerializer,
    CourseProgressSerializer,
)
from .views import (
    SubjectViewSet,
    CourseViewSet,
    ModuleViewSet,
    ContentViewSet,
    EnrollmentViewSet,
    CourseProgressView,
    MarkContentCompleteView,
    ModuleProgressView,
    LearningSessionViewSet,
)

__all__ = [
    # Serializers
    'SubjectSerializer',
    'SubjectDetailSerializer',
    'CourseListSerializer',
    'CourseDetailSerializer',
    'CourseCreateSerializer',
    'ModuleSerializer',
    'ModuleDetailSerializer',
    'ModuleCreateSerializer',
    'ContentSerializer',
    'ContentCreateSerializer',
    'ContentItemSerializer',
    'TextSerializer',
    'VideoSerializer',
    'ImageSerializer',
    'FileSerializer',
    'CourseEnrollmentSerializer',
    'EnrollmentCreateSerializer',
    'CourseWaitlistSerializer',
    'ContentProgressSerializer',
    'ModuleProgressSerializer',
    'LearningSessionSerializer',
    'MarkContentCompleteSerializer',
    'CourseProgressSerializer',
    # Views
    'SubjectViewSet',
    'CourseViewSet',
    'ModuleViewSet',
    'ContentViewSet',
    'EnrollmentViewSet',
    'CourseProgressView',
    'MarkContentCompleteView',
    'ModuleProgressView',
    'LearningSessionViewSet',
]
