# Generated by Django 5.2.6 on 2025-12-03 19:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_content_content_type_remove_content_object_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_waitlist', models.DateTimeField(auto_now_add=True)),
                ('notified_of_opening', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['priority', 'joined_waitlist'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_type',
            field=models.CharField(choices=[('open', 'Open Enrollment'), ('approval', 'Requires Approval'), ('restricted', 'Restricted Access')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Optional enrollment limit', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='waitlist_enabled',
            field=models.BooleanField(default=True, help_text='Enable waitlist when capacity reached'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='engagement_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Engagement score from 0.0 to 1.0', max_digits=3),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='total_time_spent',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('enrolled', 'Enrolled'), ('completed', 'Completed'), ('paused', 'Paused'), ('withdrawn', 'Withdrawn'), ('rejected', 'Rejected')], default='enrolled', max_length=15),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'published_at'], name='courses_cou_status_96f2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['enrollment_type'], name='courses_cou_enrollm_59d48c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject', 'status'], name='courses_cou_subject_26d194_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('max_capacity__isnull', True), ('max_capacity__gt', 0), _connector='OR'), name='positive_capacity'),
        ),
        migrations.AddField(
            model_name='coursewaitlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursewaitlist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coursewaitlist',
            index=models.Index(fields=['course', 'priority', 'joined_waitlist'], name='courses_cou_course__ef8b8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursewaitlist',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_course_waitlist'),
        ),
    ]
