# Generated by Django 5.2.6 on 2025-12-04 11:34

import django.core.validators
import embed_video.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursewaitlist_course_certificate_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='auto_play',
            field=models.BooleanField(default=False, help_text='Auto-play video when content is viewed'),
        ),
        migrations.AddField(
            model_name='video',
            name='captions_enabled',
            field=models.BooleanField(default=True, help_text='Whether captions/subtitles are available'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='minimum_watch_percentage',
            field=models.PositiveIntegerField(default=80, help_text='Minimum percentage to watch for completion (default: 80%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(blank=True, help_text='Video transcript for accessibility'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_platform',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('dailymotion', 'Dailymotion'), ('uploaded', 'Uploaded File'), ('other', 'Other Platform')], help_text='Auto-detected from URL or set manually', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, help_text='Upload video file directly', null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Video URL from YouTube, Vimeo, Dailymotion, or other platforms', null=True),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['video_platform'], name='courses_vid_video_p_4fe7df_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['owner', 'created'], name='courses_vid_owner_i_94c33d_idx'),
        ),
    ]
