# Generated by Django 5.2.6 on 2025-12-04 13:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_enhanced_video_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprogress',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('IDR', 'Indonesian Rupiah'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='IDR', help_text='Currency for pricing', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Whether this course is free or paid'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course price (set only if not free)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment gateway reference or transaction ID', max_length=100),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('refunded', 'Refunded'), ('free', 'Free Course')], default='free', max_length=15),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_free', 'price'], name='courses_cou_is_free_27475f_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['status', 'approval_requested_at'], name='courses_cou_status_daab02_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['payment_status', 'payment_date'], name='courses_cou_payment_85c9b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_free', True), ('price__isnull', True)), models.Q(('is_free', False), ('price__gt', 0), ('price__isnull', False)), _connector='OR'), name='valid_pricing'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='valid_progress_percentage'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('engagement_score__gte', 0.0), ('engagement_score__lte', 1.0)), name='valid_engagement_score'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_amount__isnull', True), ('payment_status', 'free')), models.Q(('payment_amount__isnull', False), ('payment_status__in', ['pending', 'paid', 'failed', 'refunded'])), _connector='OR'), name='valid_payment_data'),
        ),
    ]
