# Generated by Django 6.0 on 2025-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_add_indexes_for_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_type',
            field=models.CharField(choices=[('free', 'Gratis'), ('one_time', 'Beli Satuan'), ('subscription_only', 'Hanya Langganan'), ('both', 'Beli/Langganan')], default='free', help_text='How this course can be accessed', max_length=20),
        ),
    ]
