# Generated by Django 6.0 on 2025-12-26 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_add_dual_pricing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='valid_pricing',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_free', True), ('price__isnull', True), ('pricing_type', 'free')), models.Q(('is_free', True), ('price__isnull', True), ('pricing_type', 'subscription_only')), models.Q(('is_free', False), ('price__gt', 0), ('price__isnull', False), ('pricing_type', 'one_time')), models.Q(('is_free', False), ('price__gt', 0), ('price__isnull', False), ('pricing_type', 'both')), _connector='OR'), name='valid_pricing'),
        ),
    ]
