# Generated by Django 6.0 on 2026-01-01 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_update_pricing_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Course Owner'), ('co_instructor', 'Co-Instructor'), ('assistant', 'Teaching Assistant')], default='co_instructor', max_length=20)),
                ('can_edit_content', models.BooleanField(default=True, help_text='Can create/edit/delete course content')),
                ('can_manage_students', models.BooleanField(default=True, help_text='Can approve enrollments, view student progress')),
                ('can_view_analytics', models.BooleanField(default=True, help_text='Can view course analytics and earnings')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructors', to='courses.course')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_instructor_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Instructor',
                'verbose_name_plural': 'Course Instructors',
                'ordering': ['role', 'invited_at'],
                'indexes': [models.Index(fields=['course', 'user'], name='courses_cou_course__d5807b_idx'), models.Index(fields=['user', 'accepted_at'], name='courses_cou_user_id_47d7df_idx')],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
